# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{datamappify}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fred Wu"]
  s.date = %q{2010-09-24}
  s.description = %q{ActiveRecord is without doubt the de facto ORM library for Rails and many Ruby web frameworks. Many developers however, do not like database migrations and prefer to use DSL for data mapping. Datamappify is created with the sole purpose of getting rid of the DB migration headaches.}
  s.email = %q{ifredwu@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "datamappify.gemspec",
     "lib/datamappify.rb",
     "lib/datamappify/associations.rb",
     "lib/datamappify/collection.rb",
     "lib/datamappify/fake/column.rb",
     "lib/datamappify/fake/connection.rb",
     "lib/datamappify/fake/index.rb",
     "lib/datamappify/railtie.rb",
     "lib/datamappify/resource.rb",
     "lib/datamappify/schema_dumper.rb",
     "lib/tasks/datamappify.rake",
     "vendor/auto_migrations/MIT-LICENSE",
     "vendor/auto_migrations/README",
     "vendor/auto_migrations/Rakefile",
     "vendor/auto_migrations/init.rb",
     "vendor/auto_migrations/lib/auto_migrations.rb",
     "vendor/auto_migrations/lib/tasks/auto_migrations_tasks.rake",
     "vendor/auto_migrations/test/auto_migrations_test.rb"
  ]
  s.homepage = %q{http://github.com/fredwu/datamappify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib", "vendor/auto_migrations/lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Turn ActiveRecord into DataMapper (sort of)!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

